name: build_skdh
on:
  release:
    types: [published]
jobs:
  build_macosx_x86:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8, 3.7, 3.9, '3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install build and delocate
          pip install build delocate twine
        shell: bash
      - name: Build SKDH
        run: |
          # if macOS, make sure to set the environment variables so that it can find gfortran-9
          if [ "$RUNNER_OS" == "macOS" ]; then
           export FC=gfortran-9
          fi
          python -m build
      - name: Run Delocate on wheels
        run: delocate-wheel -v dist/*.whl
      - name: Upload to twine
        env:
          PYPI: ${{ secrets.PYPI }}
        run: python -m twine upload --skip-existing --verbose -u __token__ -p $PYPI dist/*
